name: Nombre comando de shell 
on: #[push]
  schedule:
    - cron:  "0/3 * * * *"
  # repository_dispatch:

jobs:
  ejecutar-comandos-shell:
    runs-on: ubuntu-latest
    steps:
      - name: cmd1
        run: echo "Hello world"
      - name: cmd2
        run: |
          node -v 
          pwd
          cat /etc/os-release
      - name: cmd3
        run: |
          import platform
          print(platform.processor())
        shell: python
  comandos-windows:
    runs-on: windows-latest
    needs: [ejecutar-comandos-shell]
    steps:
      - name: powershell
        run: Get-Location
        shell: powershell
      - name: bash
        run: pwd
        shell: bash

